graph TB
  subgraph Roots
        CoreMath
        Optimisations
        Quantum
    end

    subgraph CMS["Core Math"]
        direction TB
        Derivation -- Generalisation --> RBF --> Matern --> x["Now: Wendland"]
        CoreMath --> Derivation

        CoreMath --> UAT("Universal Approx Thm") --> DeepNets("Deep Nets are Kernels")
        CoreMath --> FeynmanPath("Feynman Path Int for Data Analysis")
    end

    subgraph Opti["Optimisation"]
        Optimisations --> GeneticOpti("Genetic Optimisation")
        Optimisations --> Annealing --> SVM2QUBO("SVM &rarr; QUBO")
             Annealing --> GradonQUBO("&#8711;<sub>&theta;</sub> &rarr; QUBO")
    end

    subgraph QLG["QuantumAlgs"]
        Quantum --> QKerns("Q Kernels")
        Quantum --> Hybrid("Hybrid Q Algs")

        Hybrid --> WPytorch("With Pytorch")
        Hybrid --> WDWave("With DWave")
    end